# Memory for the Gradle build process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# Use AndroidX libraries (required for Jetpack Compose).
android.useAndroidX=true
# Each module gets only its own R class. Faster builds.
android.nonTransitiveRClass=true
# Official Kotlin code style.
kotlin.code.style=official
