package com.lifesafety.driversafety.auth

import android.app.Activity
import android.content.Context
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.functions.FirebaseFunctions
import com.lifesafety.driversafety.R
import com.lifesafety.driversafety.alerts.FcmTokens
import com.lifesafety.driversafety.pairing.FUNCTIONS_REGION
import com.lifesafety.driversafety.trip.Notifications
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

sealed interface SignInResult {
    data object Success : SignInResult
    data object Cancelled : SignInResult
    data object NoGoogleAccount : SignInResult
    data class Failed(val error: Exception) : SignInResult
}

/**
 * Google Sign-In through Android's Credential Manager, plus the user's profile document in Firestore.
 * The role itself is written by the setRole Cloud Function, never by the app.
 */
class AuthRepository(
    private val auth: FirebaseAuth = FirebaseAuth.getInstance(),
    private val db: FirebaseFirestore = FirebaseFirestore.getInstance(),
    private val functions: FirebaseFunctions = FirebaseFunctions.getInstance(FUNCTIONS_REGION)
) {

    /** Emits the signed-in Firebase user, or null when signed out. */
    fun authUserFlow(): Flow<FirebaseUser?> = callbackFlow {
        val listener = FirebaseAuth.AuthStateListener { trySend(it.currentUser) }
        auth.addAuthStateListener(listener)
        awaitClose { auth.removeAuthStateListener(listener) }
    }

    /** Emits the user's profile (with role), or null while the user has not chosen a role yet. */
    fun profileFlow(uid: String): Flow<UserProfile?> = callbackFlow {
        val registration = db.collection("users").document(uid)
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    close(error)
                    return@addSnapshotListener
                }
                if (snapshot == null || !snapshot.exists()) {
                    trySend(null)
                    return@addSnapshotListener
                }
                val role = UserRole.fromWire(snapshot.getString("role"))
                trySend(
                    if (role == null) null else UserProfile(
                        uid = uid,
                        displayName = snapshot.getString("displayName").orEmpty(),
                        email = snapshot.getString("email"),
                        role = role
                    )
                )
            }
        awaitClose { registration.remove() }
    }

    suspend fun signInWithGoogle(activity: Activity): SignInResult {
        // default_web_client_id is generated by the google-services plugin from app/google-services.json.
        // It only exists after Google Sign-In is enabled in Firebase and the file is downloaded again.
        val googleIdOption = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(activity.getString(R.string.default_web_client_id))
            .setAutoSelectEnabled(false)
            .build()
        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()
        return try {
            val response = CredentialManager.create(activity).getCredential(activity, request)
            val credential = response.credential
            if (credential is CustomCredential &&
                credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
            ) {
                val idToken = GoogleIdTokenCredential.createFrom(credential.data).idToken
                auth.signInWithCredential(GoogleAuthProvider.getCredential(idToken, null)).await()
                SignInResult.Success
            } else {
                SignInResult.Failed(IllegalStateException("Unexpected credential type: ${credential.type}"))
            }
        } catch (e: GetCredentialCancellationException) {
            SignInResult.Cancelled
        } catch (e: NoCredentialException) {
            SignInResult.NoGoogleAccount
        } catch (e: Exception) {
            SignInResult.Failed(e)
        }
    }

    suspend fun setRole(role: UserRole) {
        functions.getHttpsCallable("setRole").call(mapOf("role" to role.wireName)).await()
    }

    suspend fun signOut(context: Context) {
        Notifications.cancelMonitoring(context)
        // While still signed in: stop push messages for this user on this phone.
        FcmTokens.unregister(context)
        auth.signOut()
        try {
            // Forget the chosen Google account so the next sign-in shows the account picker again.
            CredentialManager.create(context).clearCredentialState(ClearCredentialStateRequest())
        } catch (_: Exception) {
            // Not critical. Firebase sign-out already happened.
        }
    }
}
